In [167]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [168]:
header_names = ['make', 'address', 'all', '3d', 'our', 'over', 'remove', 'internet', 'order', 'mail', 'receive', 'will', 'people', 'report', 'addresses', 'free', 'business', 'email', 'you', 'credit', 'your', 'font', '000', 'money', 'hp', 'hpl', 'george', '650', 'lab', 'labs', 'telnet', '857', 'data', '415', '85', 'technology', '1999', 'parts', 'pm', 'direct', 'cs', 'meeting', 'original', 'project', 're', 'edu', 'table', 'conference', ';', '(', '[', '!', '$', '#', 'capital_run_length_average', 'capital_run_length_longest', 'capital_run_length_total', 'spam']
info = pd.read_csv("spambase_data/spambase.data", header=None, index_col=False, names=header_names)

In [189]:
info.tail()

make  address   all  3d   our  over  remove  internet  order  mail  \
4596  0.31        0  0.62   0  0.00  0.31       0         0      0     0   
4597  0.00        0  0.00   0  0.00  0.00       0         0      0     0   
4598  0.30        0  0.30   0  0.00  0.00       0         0      0     0   
4599  0.96        0  0.00   0  0.32  0.00       0         0      0     0   
4600  0.00        0  0.65   0  0.00  0.00       0         0      0     0   

      ...       ;      (  [      !  $  #  capital_run_length_average  \
4596  ...   0.000  0.232  0  0.000  0  0                       1.142   
4597  ...   0.000  0.000  0  0.353  0  0                       1.555   
4598  ...   0.102  0.718  0  0.000  0  0                       1.404   
4599  ...   0.000  0.057  0  0.000  0  0                       1.147   
4600  ...   0.000  0.000  0  0.125  0  0                       1.250   

      capital_run_length_longest  capital_run_length_total  spam  
4596                           3                        88     0  
4597                           4                        14     0  
4598                           6                       118     0  
4599                           5                        78     0  
4600                           5                        40     0  

[5 rows x 58 columns]

In [190]:
X = info.copy()

In [191]:
y = X.pop('spam')

In [192]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.4)

In [193]:
test_X.tail()

make  address   all  3d   our  over  remove  internet  order  mail  \
3009  0.07        0  0.07   0  0.00     0       0      0.46   0.69  0.00   
1953  0.62        0  0.00   0  0.00     0       0      0.00   0.00  0.00   
2981  0.00        0  1.61   0  0.00     0       0      0.00   0.00  0.00   
4328  0.00        0  0.34   0  0.34     0       0      0.00   0.00  0.00   
3542  0.67        0  0.00   0  0.00     0       0      0.00   0.33  0.33   

                ...             conference      ;      (      [      !      $  \
3009            ...                      0  0.142  0.175  0.032  0.000  0.021   
1953            ...                      0  0.000  0.286  0.000  0.000  0.000   
2981            ...                      0  0.000  0.283  0.000  0.000  0.000   
4328            ...                      0  0.000  0.232  0.000  0.406  0.000   
3542            ...                      0  0.056  0.280  0.168  0.056  0.000   

      #  capital_run_length_average  capital_run_length_longest  \
3009  0                       3.007                          60   
1953  0                       1.461                           4   
2981  0                       1.666                           4   
4328  0                       1.425                           6   
3542  0                       1.866                          17   

      capital_run_length_total  
3009                       791  
1953                        38  
2981                        20  
4328                        77  
3542                       112  

[5 rows x 57 columns]

In [194]:
test_y.head()

1917    0
2293    0
1976    0
787     1
1586    1
Name: spam, dtype: int64

In [195]:
classifier = MultinomialNB()

In [196]:
classifier.fit(train_X, train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [197]:
classifier.score(train_X, train_y)

0.78405797101449271

In [198]:
classifier.score(test_X, test_y)

0.78326996197718635

In [200]:
classifier.predict(test_X.loc[1917])

array([0])

In [201]:
classifier.predict(test_X.loc[1586])

array([1])

###Hard Mode

In [202]:
X2 = info.copy()

In [203]:
y2 = X2.pop('spam')
z = X2.pop('capital_run_length_average')
z1 = X2.pop('capital_run_length_total')
z2 = X2.pop('capital_run_length_longest')

In [204]:
train_X2, test_X2, train_y2, test_y2 = train_test_split(X2, y2, test_size=0.4)

In [205]:
classifier2 = MultinomialNB()

In [206]:
classifier2.fit(train_X2, train_y2)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [207]:
classifier2.score(train_X2, train_y2)

0.87572463768115938

In [208]:
classifier2.score(test_X2, test_y2)

0.87561108093427487

In [210]:
test_y2.head()

2815    0
4502    0
433     1
995     1
4544    0
Name: spam, dtype: int64

In [211]:
classifier2.predict(test_X2.loc[433])

array([1])

In [212]:
classifier2.predict(test_X2.loc[2815])

array([0])

Taking out the features which count the capital letters (avg, in a row, and total) gives a more accurate filter.